// // Data pemain
// export const players = [
//   {
//     id: '1',
//     name: 'David da Silva',
//     image: '/player/dds.jpg',
//     position: 'Striker',
//     bio: 'David da Silva adalah penyerang tajam asal Brasil yang menjadi andalan Persib Bandung.',
//   // },
//   {
//     id: '2',
//     name: 'Marc Klok',
//     image: '/player/klok.jpg',
//     position: 'Midfielder',
//     bio: 'Marc Klok adalah gelandang kreatif yang punya visi bermain luar biasa.',
//   },
//   {
//     id: '3',
//     name: 'Beckham Putra',
//     image: '/player/beckam.jpg',
//     position: 'Winger',
//     bio: 'Beckham Putra Nugraha adalah pemain muda berbakat Persib dengan kecepatan luar biasa.',
//   },
//   {
//     id: '4',
//     name: 'Nick Kuipers',
//     image: '/player/nickkuiperss.jpg',
//     position: 'Defender',
//     bio: 'Nick Kuipers adalah bek tangguh asal Belanda yang memperkuat lini belakang Persib.',
//   },
//   {
//     id: '5',
//     name: 'Kevin Ray Mendoza',
//     position: 'Goalkeeper',
//     image: '/player/kevin.jpg',
//     bio: 'Penjaga gawang tangguh asal Filipina tak tergantikan di bawah mistar gawang Persib.',
//   },
//   {
//   id: '6',
//   name: 'Ciro Alves',
//   position: 'Forward',
//   image: '/player/ciro.jpg',
//   bio: 'Ciro Alves adalah penyerang lincah asal Brasil yang menjadi motor serangan Persib.',
//   },
//   {
//     id: '7',
//     name: 'Tyronne del Pino',
//     position: 'Midfielder',
//     image: '/player/tyronne.jpg',
//     bio: 'Tyronne del Pino adalah gelandang kreatif asal Spanyol yang memperkuat lini tengah Persib.',
//   },
//   {
//     id: '8',
//     name: 'Gustavo Franca',
//     position: 'Forward',
//     image: '/player/gustavo.jpg',
//     bio: 'Gustavo Franca adalah striker muda asal Brasil yang memiliki insting gol tinggi.',
//   },
//   {
//     id: '9',
//     name: 'Kakang Rudianto',
//     position: 'Defender',
//     image: '/player/kakang.jpg',
//     bio: 'Kakang Rudianto adalah bek muda potensial hasil akademi Persib yang tampil kokoh di lini belakang.',
//   },
//   {
//     id: '10',
//     name: 'Edo Febriansyah',
//     position: 'Defender',
//     image: '/player/edo.jpg',
//     bio: 'Edo Febriansyah adalah bek sayap energik dengan kemampuan menyerang dan bertahan yang seimbang.',
//   },
//   {
//     id: '11',
//     name: 'Dimas Drajad',
//     position: 'Striker',
//     image: '/player/dimas.jpg',
//     bio: 'Dimas Drajad adalah penyerang lokal tajam yang mengandalkan kecepatan dan naluri mencetak gol.',
//   },
//   {
//     id: '12',
//     name: 'Robi Darwis',
//     position: 'Midfielder',
//     image: '/player/robi.jpg',
//     bio: 'Robi Darwis adalah gelandang bertahan muda yang tangguh dan disiplin dalam menjaga lini tengah.',
//   },
//   {
//     id: '13',
//     name: 'Dedi Kusnandar',
//     position: 'Midfielder',
//     image: '/player/dedi.jpg',
//     bio: 'Dedi Kusnandar adalah gelandang bertahan yang tangguh dan disiplin dalam menjaga lini tengah.',
//   },

// ];